<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="2" name="pytest" skips="0" tests="4" time="0.047">
    <testcase classname="test.test_function" file="test/test_function.py" line="19" name="test_function_fail" time="0.0012459754943847656">
        <properties>
            <property name="test_id" value="1501"/>
        </properties>
        <failure message="assert False">topology = &apos;a_topology&apos;

    @pytest.mark.test_id(1501)
    @pytest.mark.initialize(
        initialize,
        args=(&apos;init1&apos;, ),
        kwargs={&apos;kwarg1&apos;: &apos;kwargs1init&apos;}
    )
    @pytest.mark.terminate(
        terminate,
        args=(&apos;term1&apos;, ),
        kwargs={&apos;kwarg1&apos;: &apos;kwargs1term&apos;}
    )
    def test_function_fail(topology):
        print()
        print(&apos;Test:&apos;)
        print(&apos;topology = {}&apos;.format(topology))
&gt;       assert False
E       assert False

../../../test/test_function.py:35: AssertionError</failure>
    </testcase>
    <testcase classname="test.test_function" file="test/test_function.py" line="37" name="test_function_pass" time="0.0010669231414794922">
        <properties>
            <property name="test_id" value="1502"/>
        </properties>
    </testcase>
    <testcase classname="test.test_function2" file="test/test_function2.py" line="19" name="test_function_fail" time="0.0019729137420654297">
        <properties>
            <property name="test_id" value="1601"/>
        </properties>
        <failure message="assert False">topology = &apos;a_topology&apos;

    @pytest.mark.test_id(1601)
    @pytest.mark.initialize(
        initialize,
        args=(&apos;init1&apos;, ),
        kwargs={&apos;kwarg1&apos;: &apos;kwargs1init&apos;}
    )
    @pytest.mark.terminate(
        terminate,
        args=(&apos;term1&apos;, ),
        kwargs={&apos;kwarg1&apos;: &apos;kwargs1term&apos;}
    )
    def test_function_fail(topology):
        print()
        print(&apos;Test:&apos;)
        print(&apos;topology = {}&apos;.format(topology))
&gt;       assert False
E       assert False

../../../test/test_function2.py:35: AssertionError</failure>
    </testcase>
    <testcase classname="test.test_function2" file="test/test_function2.py" line="37" name="test_function_pass" time="0.00044608116149902344">
        <properties>
            <property name="test_id" value="1602"/>
        </properties>
    </testcase>
</testsuite>